[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ttkthemes",
    "opencv-contrib-python",
    "Pillow",
    'evdev; sys_platform == "Linux"',
    'python-uinput; sys_platform == "Linux"'
]
build-backend = "setuptools.build_meta"
